FROM node:10.15.1-alpine AS Front-End-Builder

# Copy the files needed for dependency management and
# TypeScript criteria into the container
COPY package-lock.json package.json tsconfig.json ./

# Install the needed dependencies for the front-end
RUN npm install

# Copy the Typescript React files and assets into the container
COPY ./src ./src
COPY ./public ./public

# Build the typescript react project into the
# CSS, HTML, and JavaScript and bundle the assets
RUN npm run build

FROM nginx:latest

# Explicitly expose port 80
EXPOSE 80

# Remove the default files in the /usr/share/nginx/html/ directory
RUN rm -rf /usr/share/nginx/html/*

# Copy the built files into the nginx container
COPY --from=Front-End-Builder /build /usr/share/nginx/html

# Copy the nginx configuration file into the container
COPY ./back-end/file-server/nginx.conf /etc/nginx/nginx.conf

# Copy your certificate and secret files into the container
# COPY ${HTTPS_CERTIFICATE} /etc
# COPY ${HTTPS_SECRET} /etc
