version: "3.5"

services:
  api-server:
    build: ./back-end/api-server/
    expose:
      - "80"
    networks:
      - PROJECT-network
    restart: always

  file-server:
    build: .
    ports:
      - "80:80"
    networks:
      - PROJECT-network
    restart: always

networks:
  PROJECT-network:
    name: PROJECT-network
