version: "3.5"

services:
  api-server:
    build: ./back-end/api-server/
    expose:
      - "80"
    networks:
      - PROJECT-network-internal
    restart: always

  file-server:
    build: .
    expose:
      - "80"
    networks:
      - PROJECT-network-internal
    restart: always

networks:
  PROJECT-network-internal:
    name: PROJECT-network-external
