FROM node:10.15.1-alpine AS Front-End-Builder

# Copy the files needed for dependency management
COPY package-lock.json package.json ./

# Install the needed dependencies for the front-end
RUN npm install

# Copy the Typescript React files and assets into the container
COPY ./src ./src
COPY ./public ./public

# Copy files for build criteria into the container
COPY tsconfig.json ./

# Build the typescript react project into the
# CSS, HTML, and JavaScript and bundle the assets
RUN npm run build


FROM golang:1.12.5-alpine3.9 AS File-Server-Builder

# Add ca-certificates to get the proper certs for making requests,
# gcc and musl-dev for any cgo dependencies, and
# git for getting dependencies residing on github
RUN apk update && \
    apk add --no-cache ca-certificates gcc git musl-dev

WORKDIR /

COPY ./back-end/file-server/go.mod ./back-end/file-server/go.sum ./

# Install all of the nessesary dependencies
RUN go mod download

COPY ./back-end/file-server/file-server.go .

# Compile program statically with local dependencies
RUN env CGO_ENABLED=0 go build -ldflags '-extldflags "-static"' -a -v -o file-server

# Last stage of build, adding in files and running
# newly compiled webserver
FROM scratch

# Copy the built files into the file-server container
COPY --from=Front-End-Builder /build /static

# Copy the Go program compiled in the second stage
COPY --from=File-Server-Builder /file-server /

# Add HTTPS Certificates for making HTTP requests from the webserver
COPY --from=File-Server-Builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

# Expose ports 80 to host machine
EXPOSE 80

# Run program
ENTRYPOINT ["/file-server"]
